app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

stable:
    resource: "@AppBundle/Controller/StableController.php"
    type:     annotation
    prefix:   /stable